# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models

from ..data import domain_names


def create_disposable_domain_names(apps, schema_editor):
    DisposableDomainName = apps.get_model('indisposable_domain_name', 'DisposableDomainName')

    ddns = [DisposableDomainName(value=name) for name in domain_names]
    DisposableDomainName.objects.bulk_create(ddns)


def delete_disposable_domain_names(apps, schema_editor):
    DisposableDomainName = apps.get_model('indisposable_domain_name', 'DisposableDomainName')

    DisposableDomainName.objects.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableDomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Domain name that should be blacklisted', max_length=255, unique=True, verbose_name='Domain Name')),
            ],
        ),
        migrations.RunPython(
            create_disposable_domain_names,
            delete_disposable_domain_names,
        ),
    ]
